# .github/ISSUE_TEMPLATES/config.yml
blank_issues_enabled: false
contact_links:
  - name: Custom Issue
    url: https://github.com/IBM-DevOps-Capstone-Project/issues/new?template=storytemplate.md
    about: Use this template for user stories
